remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

title: [Betrands Paradox]
description:
[Consider an equilateral triangle inscribed in a circle. 
Suppose a chord of the circle is chosen at random. 
What is the probability that the chord is longer than a side of the triangle?]
